### ISSUE TITLE
Connecting multiple buses to Fleet Manager in one process.

### ISSUE THREAD

**Issue by levirak** [rebus-org/FleetManager#1]
I'm in the process of investigating what it would take for us to use Fleet Manager with our current setup, but I'm running onto a pretty big problem: we can't find a good way to connect more than one bus per process to Fleet Manager.

What I gather is that `Rebus.FleetManager` makes use of a buffer directory to queue up messages and store some auxiliary data. The problem is that each instance of a bus that has Fleet Manager enabled apparently expects total control of that directory for its entire lifetime. The effect of this is that we cannot use more than one bus in a single process without giving them separate directories.

And while we can change the buffer directory, how we use our buses makes it hard to ensure that each bus gets a unique buffer directory _and_ gets the same directory every time. While we could do this assignment manually, we're looking for a more robust solution.

Do you have any suggestions on how to handle connecting multiple buses in the same process to Fleet Manager?

**Comment by mookid8000** [comment]
When re-visiting the local buffering mechanism, maybe [this PR](https://github.com/microsoft/FASTER/pull/177) has been merged? If so, maybe it would make sense to use FASTER log instead of the self-made buffering thing....?

**Comment by mookid8000** [comment]
File-based buffering has now been removed, drastically simplifying running multiple Rebus instances in the same process! 🙂
