### ISSUE TITLE
Have Team management UI to delete teams

### ISSUE THREAD

**Issue by zogamorph** [rebus-org/FleetManager#118]
To have a screen that would allow us to remove teams that have been create in error or no longer need.  Without having to use a cli, we are using fleetmanger in Azure with app services using a docker image.  Getting a cli to run against our instance is not straight forward.

**Comment by mookid8000** [comment]
Fleet Manager 4.24.0 has an "Archive" button under the "Admin" tab under team administration.

![image](https://user-images.githubusercontent.com/32968/174074170-55ec5b83-ae2a-4c68-9d1d-bd6c7673615a.png)

Only team administrators can click it. 🙂

**Comment by ghost** [comment]
Nice - thanks, @mookid8000 🚀
