### ISSUE TITLE
dependency events (post) in app insights

### ISSUE THREAD

**Issue by Qball1337** [rebus-org/FleetManager#120]
We recently integrated fleet manager in our project and noticed hunderds of dependency events per minute in app insights. All of them are a post to either /api/bulk or /api/command. This is coming from the webjob (with rebus) to the fleet manager application. Is this normal behaviour or are we missing some configuration? This is happening without any messages beeing processed, meaning the fleet manager is idle. 

Kind regards

**Comment by mookid8000** [comment]
Hi @Qball1337 , the Rebus.FleetManager plugin will periodically forward events in the form of heartbeats and metrics to Fleet Manager, and it will long-poll for commands (i.e. instructions from Fleet Manager like "retry this message", etc.).

Event forwarding happens every couple of seconds, and command long-polling lasts for ~30s for every request.

If you're seeing hundreds of requests per minute from a single, idle Rebus instance, it sounds like something is off.

Please get in touch via Slack, and then we'll figure out what's wrong 🙂
