### ISSUE TITLE
Finish Slack integration

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/FleetManager#33]
The currently available Slack integrations are half-baked. Finish them

- [x] Ensure alert rules with Slack notifications can roundtrip properly
- [x] Add queue name patterns
- [x] Finish handling of Slack notifications on the server
- [x] Add modal "Are you sure?" dialog when clicking "x Remove" on an alert rule
- [x] Prevent deletion of an integration currently in use by one or more alert rules
- [x] Add deeplink to failed message to text posted on Slack

**Comment by anhnicky66** [comment]
@mookid8000 will the dialog displays only yes/no buttons or prompt an input asking for typing "Delete" to confirm the action?

**Comment by mookid8000** [comment]
It's ok with simple yes/no buttons.

I actually think I made something very similar on the Team details page, where it prompts for confirmation whenever you try to promote/demote team members.
