### ISSUE TITLE
Redesign activity overview box

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/FleetManager#58]
The account box from the Activity Overview:

![image](https://user-images.githubusercontent.com/32968/81542616-3d78b900-9375-11ea-8097-a0e899a45484.png)

could use some more fields 🙂 

I want to include three additional counts:
* number of queues green
* number of machines green
* number of active alerts

To make room for these three numbers, I thought that it would maybe be possible to replace the texts "Messages", "Exceptions" and "Errors" with little icons, and then do the same for the three new counts.... something like this:

![image](https://user-images.githubusercontent.com/32968/81543746-cd6b3280-9376-11ea-8131-dcd9b758d0c2.png)

(btw. the correponding FA icons are "check", "bolt", "times", "database", "server" and "bell")

I'm not sure though that this is how it should look, so I would like to iterate a couple of times, so here are the tasks:

### Anh

- [x] Sketch draft of what it could look like
- [x] Implement prototype in DEV

### Mogens

- [x] Provide fields mentioned by @anhnicky66 
- [x] Run with it for a while
- [x] Search your feelings

**Comment by anhnicky66** [comment]
@mookid8000 I'm using these missing fields (under result from account/overview?stats=today) in the template at the moment: `queues`, `machines`, `alerts`, `totalQueues`, `totalMachines`.
