### ISSUE TITLE
Add links to overview

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/FleetManager#69]
In the account overview, the following should be made into links:

![image](https://user-images.githubusercontent.com/32968/88287789-1898ae80-ccf3-11ea-8f7d-5d875c73cc83.png)

1: Should go to Failed Messages with an absolute time filter for the entire day
2: Should go to Queues Overview
3: Should go to Machines Overview
4: Should go to Active Alerts

The links should be "hidden", meaning that they should look like they do now, but when the mouse hovers over a link, the cursor should become a pointer, and maybe some kind of symbol should indicate that this is actually a link.

**Comment by mookid8000** [comment]
hey @anhnicky66 , just in case you haven't noticed: WHen clicking one of the links BEFORE having had an active account context

![image](https://user-images.githubusercontent.com/32968/91974869-c8176680-ed1e-11ea-8b38-0c7211fe4098.png)

it looks like this:

![image](https://user-images.githubusercontent.com/32968/91974989-f9903200-ed1e-11ea-8307-521c06329f16.png)

Also, if one has an active account context (e.g. Fleet Manager TEST) and clicking one of the links for another account, the account context is not changed (staying at Fleet Manager TEST in this case, even though I clicked a link for Fleet Manager DEV)

**Comment by anhnicky66** [comment]
@mookid8000 oh... I'll look into this
