### ISSUE TITLE
SQL Server persistence, clustered index key too large

### ISSUE THREAD

**Issue by rohnitz** [rebus-org/FleetManager#74]
In all tables the Id column is defined as nvarchar(850) and is used as key for the clustered index, this will generate the following warning when the table is created:
_Warning! The maximum key length for a clustered index is 900 bytes. The index 'PK__Accounts__3214EC0707647A65' has maximum length of 1700 bytes. For some combination of large values, the insert/update operation will fail._

If you want to use nvarchar (whish is a terrible choice on the other hand) as key for the clustered index it´s length can bee max 450 characters.

**Comment by mookid8000** [comment]
This is definitely something I'll have a look at soon!

**Comment by mookid8000** [comment]
Fixed in 4.0, which will be out soon :)
