### ISSUE TITLE
Unrecoverable failure after heavy(?) load

### ISSUE THREAD

**Issue by ajtowf** [rebus-org/FleetManager#78]
[fm-logs.zip](https://github.com/rebus-org/FleetManager/files/5154707/fm-logs.zip)

We went live with fleetmanager in our QA environment for the first time where we actually have some load. We did this on friday, produced quite many events, sometime during the weekend we believe that fleetmanager exploded :-)

On monday we could not sign into fleet, or we could sign in, but could not select our account from the initial dashboard. We've restarted the service but from looking at the logs this doesn't seem to recover. 

Internal db seems boken?

**Comment by mookid8000** [comment]
I'm afraid your hunch might turn out to be correct.... looks like it all starts under fairly heavy load (couple of 100s of events ingested per second 👉 lots of activity in persistent projections) where Fleet Manager's embedded database, LiteDB, gets a fit during a defragmentation that happens as part of a flush (at 2020-08-29 23:24:52.889 +02:00):
```
System.ArgumentException: An entry with the same key already exists.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at LiteDB.Engine.BasePage.Defrag()
(...)
```
This error seems to persist until some time early on 2020-08-30, when suddenly messages along the lines of 
```
LiteDB.LiteException: Invalid Data on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 1959. ShareCounter: -1. 
```
start to make it into the log. 😐 Then all kinds of fun starts, and LiteDB throws messages like
```
System.InvalidCastException: Unable to cast object of type 'LiteDB.Engine.HeaderPage' to type 'LiteDB.Engine.DataPage'.

LiteDB.LiteException: Invalid Data on 0. Full zero: True. Page Type: Empty. Prev/Next: 0/0. UniqueID: 5674. ShareCounter: -1. 

LiteDB.LiteException: Invalid Collection on 1365001555. Full zero: False. Page Type: 65. Prev/Next: 1768835387/1818323316. UniqueID: 7045. ShareCounter: 9. 

System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
```
until finally it decides to settle with
```
LiteDB.LiteException: Maximum number of transactions reached
```
as its favorite error, which it keeps repeating from 2020-08-30 02:57:05.536 +02:00 and the rest of the time, until the process is shut down. After a restart, LiteDB just goes
```
System.NotSupportedException: BSON type not supported
```
when trying to query with it.

This is very alarming. I need to investigate this further, ultimately maybe ending up replacing the use of LiteDB by something else.

**Comment by mookid8000** [comment]
Hi @ajtowf , in Fleet Manager 3.10.4 (which is available through the installer) I've replaced all use of LiteDB with an async wrapper, LiteDB-async – it effectively serializes all access to each database instance, which I believe will work around the issue with the corrupted data file.

Unfortunately, I think you'll need to completely wipe your current LiteDB data files, so the directory location pointed to by "views" app setting must be deleted.

Let me know if this solves the issue. I'll mark this one as closed, and I'll get back to you on Slack for some more news 🙂

**Comment by ajtowf** [comment]
Thanks, we'll give it a try right away.
