### ISSUE TITLE
Frequent sql-queries

### ISSUE THREAD

**Issue by rohnitz** [rebus-org/FleetManager#79]
I work with the same installation as in #78 
After we went live in QA environment i have been monitoring the SLQ-server. There i have noticed two sql-queries against the FleetManager database that are extremly frequent.

`WITH TopCTE AS (    
SELECT  TOP 1 [Document], [LockedUntil], [AccountId], [ClientId]
FROM  [Commands] M WITH (ROWLOCK, READPAST, READCOMMITTEDLOCK)
WHERE  M.[LockedUntil] <= sysdatetimeoffset()          
AND M.[AccountId] = @accountId          
AND M.[ClientId] = @clientId    
ORDER    BY    [CreatedAt] ASC  )  
UPDATE  TopCTE WITH (ROWLOCK, READCOMMITTEDLOCK)  
SET    [LockedUntil] = DATEADD(ss, @lockDurationSeconds, sysdatetimeoffset())  
OUTPUT  inserted.*`

`WITH TopCTE AS (    
SELECT  TOP 1 [Document], [LockedUntil], [AccountId]    
FROM  [Commands] M WITH (ROWLOCK, READPAST, READCOMMITTEDLOCK)    
WHERE  M.[LockedUntil] <= sysdatetimeoffset()          
AND M.[AccountId] = @accountId    
ORDER    BY    [CreatedAt] ASC  )  
UPDATE  TopCTE WITH (ROWLOCK, READCOMMITTEDLOCK)  
SET    [LockedUntil] = DATEADD(ss, @lockDurationSeconds, sysdatetimeoffset())  
OUTPUT  inserted.*`

Each of these queries are execuded around 2800 times / minute.

I have traced the sessions that is executing and they are coming from "FleetManager.WindowsService.exe"

The queries in them self are not so heavy, but as they are so frequent they still consume resources.

So i was wondering if this is as intended, otherwise it might be a good idea to try to lower the frequency.

**Comment by mookid8000** [comment]
This is because Fleet Manager uses your SQL Server as a queue for commands to your Rebus instances.

I can see how this is not convenient, so we'll consider using an alternative storage for the commands. Stay tuned 🙂

**Comment by mookid8000** [comment]
Fleet Manager 3.10.4 (which was made available a few minutes ago) can use the file system as the command database. This means that you can set the "commands" connection string to a directory, and then it'll use that instead. 

That should give your SQL Server some relief 🙂
