### ISSUE TITLE
Registering same queue with different casing breaks Fleetmanager UI status reports for all queues

### ISSUE THREAD

**Issue by codedoings** [rebus-org/FleetManager#81]
Rebus package version: 6.1.0
Rebus.FleetManager version: 4.0.0-rc17
Fleetmanager version: 3.10.4

Steps to reproduce (fairly certain):

1. Setup and start a rebus queue (called "queue A" from now on) that uses fleetmanager
2. Ensure queue A shows up in fleetmanager with green status
3. Setup and start a rebus queue (called "queue B" from now on) that uses fleetmanager
4. Ensure queue B shows up in fleetmanager with green status
5. Stop service bus for queue B
6. Change name of queue "B" to "b" and start the bus/queue again
7. After a while, fleetmanager UI seems to start reporting yellow status for ALL queues, even queue A and the UI doesnt seem to respond well i.e to the "Hide" command on queues.

We are seeing exceptions in the fleetmanager logs:
2020-10-02 10:35:00.203 +02:00|WRN|persistentprojections||Topos.Consumer.MessageHandler|Exception when executing message handler - waiting 00:00:02 before trying again
LiteDB.Async.LiteAsyncException: LiteDb encounter an error. Details in the inner exception. ---> LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '"<_**teamid and queuename omitted here**_>"'.
   at LiteDB.Engine.IndexService.AddNode(CollectionIndex index, BsonValue key, PageAddress dataBlock, Byte level, IndexNode last)

Im not really sure what kind of behavior I expected when one changed the queue name casing though all queues starting reporting yellow status was unexpected. We solved the issue by manually deleting the fleetmanager buffer files on the server where queue B bus was hosted. I am also no sure if the error handling mechanisms for queue A are working properly even though the status is yellow for the queue.

**Comment by mookid8000** [comment]
OK now I've identified the issue: It's caused by the fact that LiteDB (the embedded database that is being used for projections, when you don't have MongoDB) defaults to use a case-insensitive collation.

Luckily, it seems it can be fixed simply by rebuilding the database files with a proper collation.

We're working on a fix. Stay tuned 🙂
