### ISSUE TITLE
Clicking on a message in failed messages throw errors

### ISSUE THREAD

**Issue by anhnicky66** [rebus-org/FleetManager#89]
aurelia-fetch-client.js?e7a5:199 GET https://fm2-dev.azurewebsites.net/ui/message/sequence?correlationId=7bef03f9-5ee4-425e-9980-7750418822ed 404 (Not Found)
eval @ aurelia-fetch-client.js?e7a5:199
tryCatcher @ VM2286 154:5413
Promise._settlePromiseFromHandler @ VM2286 154:3409
Promise._settlePromise @ VM2286 154:3466
Promise._settlePromise0 @ VM2286 154:3511
Promise._settlePromises @ VM2286 154:3591
_drainQueueStep @ VM2286 154:145
_drainQueue @ VM2286 154:138
Async._drainQueues @ VM2286 154:154
Async.drainQueues @ VM2286 154:67
eval @ VM2286 154:4663
attributes (async)
eval @ VM2286 154:4649
attributes (async)
scheduleToggle @ VM2286 154:4657
schedule @ VM2286 154:4666
Async._queueTick @ VM2286 154:163
AsyncSettlePromises @ VM2286 154:128
Promise._fulfill @ VM2286 154:3537
Promise._resolveCallback @ VM2286 154:3328
resolve @ VM2286 154:5059
Promise.then (async)
tryCatcher @ VM2286 154:5413
doThenable @ VM2286 154:5049
tryConvertToPromise @ VM2286 154:5014
Promise._resolveCallback @ VM2286 154:3327
Promise._settlePromiseFromHandler @ VM2286 154:3421
Promise._settlePromise @ VM2286 154:3466
Promise._settlePromise0 @ VM2286 154:3511
Promise._settlePromises @ VM2286 154:3591
_drainQueueStep @ VM2286 154:145
_drainQueue @ VM2286 154:138
Async._drainQueues @ VM2286 154:154
Async.drainQueues @ VM2286 154:67
eval @ VM2286 154:4663
attributes (async)
eval @ VM2286 154:4649
attributes (async)
scheduleToggle @ VM2286 154:4657
schedule @ VM2286 154:4666
Async._queueTick @ VM2286 154:163
AsyncSettlePromises @ VM2286 154:128
Promise._fulfill @ VM2286 154:3537
Promise._resolveCallback @ VM2286 154:3328
resolve @ VM2286 154:5059
Promise.then (async)
tryCatcher @ VM2286 154:5413
doThenable @ VM2286 154:5049
tryConvertToPromise @ VM2286 154:5014
Promise.cast @ VM2286 154:3084
applyInterceptors @ aurelia-fetch-client.js?e7a5:324
processResponse @ aurelia-fetch-client.js?e7a5:312
eval @ aurelia-fetch-client.js?e7a5:204
tryCatcher @ VM2286 154:5413
Promise._settlePromiseFromHandler @ VM2286 154:3409
Promise._settlePromise @ VM2286 154:3466
Promise._settlePromise0 @ VM2286 154:3511
Promise._settlePromises @ VM2286 154:3591
_drainQueueStep @ VM2286 154:145
_drainQueue @ VM2286 154:138
Async._drainQueues @ VM2286 154:154
Async.drainQueues @ VM2286 154:67
eval @ VM2286 154:4663
attributes (async)
eval @ VM2286 154:4649
attributes (async)
scheduleToggle @ VM2286 154:4657
schedule @ VM2286 154:4666
Async._queueTick @ VM2286 154:163
AsyncInvoke @ VM2286 154:123
Promise._then @ VM2286 154:3152
Promise.then @ VM2286 154:3016
importViewModelResource @ aurelia-templating.js?f83c:3530
ensureViewModel @ aurelia-templating.js?f83c:4856
DialogService.ensureViewModel @ dialog-service.js?1aa4:62
DialogService.open @ dialog-service.js?1aa4:131
eval @ message-dialog.js?3b90:25
Promise._execute @ VM2286 154:1054
Promise._resolveFromExecutor @ VM2286 154:3380
Promise @ VM2286 154:2965
open @ message-dialog.js?3b90:24
showMessage @ messages-failed-page.js?14a7:268
evaluate @ aurelia-binding.js?1bbb:1517
callSource @ aurelia-binding.js?1bbb:5241
handleEvent @ aurelia-binding.js?1bbb:5250
handleEvent @ aurelia-binding.js?1bbb:3315
VM2286 154:1633 Warning: a promise was rejected with a non-error: [object Response]    at Rest.request (webpack-internal:///aurelia-api:50:52)    at Rest.find (webpack-internal:///aurelia-api:66:17)    at ApiClient.get (webpack-internal:///4:33:28)    at MessageDialogViewModel.getSequence (webpack-internal:///resources/dialogs/message-dialog/message-dialog-view-model:102:31)    at eval (webpack-internal:///resources/dialogs/message-dialog/message-dialog-view-model:50:19)From previous event:    at MessageDialogViewModel.activate (webpack-internal:///resources/dialogs/message-dialog/message-dialog-view-model:48:113)    at tryActivateViewModel (webpack-internal:///13:4848:28)From previous event:    at CompositionEngine.createController (webpack-internal:///13:4907:42)    at CompositionEngine._createControllerAndSwap (webpack-internal:///13:4879:17)    at CompositionEngine.compose (webpack-internal:///13:4981:19)    at DialogService.composeAndShowDialog (webpack-internal:///832:87:39)    at eval (webpack-internal:///832:149:26)From previous event:    at DialogService.open (webpack-internal:///832:144:12)    at eval (webpack-internal:///665:36:33)From previous event:    at MessageDialog.open (webpack-internal:///665:35:23)    at MessagesFailedController.showMessage (webpack-internal:///pages/messages/messages-failed-page:352:28)    at CallScope.evaluate (webpack-internal:///51:1612:19)    at Listener.callSource (webpack-internal:///51:5336:40)    at Listener.handleEvent (webpack-internal:///51:5345:10)    at DelegateHandlerEntry.handleEvent (webpack-internal:///51:3410:22)
printWarning @ VM2286 154:1633
formatAndLogError @ VM2286 154:1349
warn @ VM2286 154:1244
Promise._warn @ VM2286 154:794
Promise._rejectCallback @ VM2286 154:3368
Promise._settlePromiseFromHandler @ VM2286 154:3418
Promise._settlePromise @ VM2286 154:3466
Promise._settlePromise0 @ VM2286 154:3511
Promise._settlePromises @ VM2286 154:3591
_drainQueueStep @ VM2286 154:145
_drainQueue @ VM2286 154:138
Async._drainQueues @ VM2286 154:154
Async.drainQueues @ VM2286 154:67
eval @ VM2286 154:4663
attributes (async)
eval @ VM2286 154:4649
attributes (async)
scheduleToggle @ VM2286 154:4657
schedule @ VM2286 154:4666
Async._queueTick @ VM2286 154:163
AsyncSettlePromises @ VM2286 154:128
Promise._fulfill @ VM2286 154:3537
Promise._resolveCallback @ VM2286 154:3328
resolve @ VM2286 154:5059
Promise.then (async)
tryCatcher @ VM2286 154:5413
doThenable @ VM2286 154:5049
tryConvertToPromise @ VM2286 154:5014
Promise.cast @ VM2286 154:3084
applyInterceptors @ aurelia-fetch-client.js?e7a5:324
processResponse @ aurelia-fetch-client.js?e7a5:312
eval @ aurelia-fetch-client.js?e7a5:204
tryCatcher @ VM2286 154:5413
Promise._settlePromiseFromHandler @ VM2286 154:3409
Promise._settlePromise @ VM2286 154:3466
Promise._settlePromise0 @ VM2286 154:3511
Promise._settlePromises @ VM2286 154:3591
_drainQueueStep @ VM2286 154:145
_drainQueue @ VM2286 154:138
Async._drainQueues @ VM2286 154:154
Async.drainQueues @ VM2286 154:67
eval @ VM2286 154:4663
attributes (async)
eval @ VM2286 154:4649
attributes (async)
scheduleToggle @ VM2286 154:4657
schedule @ VM2286 154:4666
Async._queueTick @ VM2286 154:163
AsyncSettlePromises @ VM2286 154:128
Promise._fulfill @ VM2286 154:3537
Promise._resolveCallback @ VM2286 154:3328
resolve @ VM2286 154:5059
Promise.then (async)
tryCatcher @ VM2286 154:5413
doThenable @ VM2286 154:5049
tryConvertToPromise @ VM2286 154:5014
Promise._resolveCallback @ VM2286 154:3327
Promise._settlePromiseFromHandler @ VM2286 154:3421
Promise._settlePromise @ VM2286 154:3466
Promise._settlePromise0 @ VM2286 154:3511
Promise._settlePromises @ VM2286 154:3591
_drainQueueStep @ VM2286 154:145
_drainQueue @ VM2286 154:138
Async._drainQueues @ VM2286 154:154
Async.drainQueues @ VM2286 154:67
eval @ VM2286 154:4663
attributes (async)
eval @ VM2286 154:4649
attributes (async)
scheduleToggle @ VM2286 154:4657
schedule @ VM2286 154:4666
Async._queueTick @ VM2286 154:163
AsyncSettlePromises @ VM2286 154:128
Promise._fulfill @ VM2286 154:3537
Promise._resolveCallback @ VM2286 154:3328
resolve @ VM2286 154:5059
Promise.then (async)
tryCatcher @ VM2286 154:5413
doThenable @ VM2286 154:5049
tryConvertToPromise @ VM2286 154:5014
Promise.cast @ VM2286 154:3084
applyInterceptors @ aurelia-fetch-client.js?e7a5:324
processResponse @ aurelia-fetch-client.js?e7a5:312
eval @ aurelia-fetch-client.js?e7a5:204
tryCatcher @ VM2286 154:5413
Promise._settlePromiseFromHandler @ VM2286 154:3409
Promise._settlePromise @ VM2286 154:3466
Promise._settlePromise0 @ VM2286 154:3511
Promise._settlePromises @ VM2286 154:3591
_drainQueueStep @ VM2286 154:145
_drainQueue @ VM2286 154:138
Async._drainQueues @ VM2286 154:154
Async.drainQueues @ VM2286 154:67
eval @ VM2286 154:4663
attributes (async)
eval @ VM2286 154:4649
attributes (async)
scheduleToggle @ VM2286 154:4657
schedule @ VM2286 154:4666
Async._queueTick @ VM2286 154:163
AsyncInvoke @ VM2286 154:123
Promise._then @ VM2286 154:3152
Promise.then @ VM2286 154:3016
importViewModelResource @ aurelia-templating.js?f83c:3530
ensureViewModel @ aurelia-templating.js?f83c:4856
DialogService.ensureViewModel @ dialog-service.js?1aa4:62
DialogService.open @ dialog-service.js?1aa4:131
eval @ message-dialog.js?3b90:25
Promise._execute @ VM2286 154:1054
Promise._resolveFromExecutor @ VM2286 154:3380
Promise @ VM2286 154:2965
open @ message-dialog.js?3b90:24
showMessage @ messages-failed-page.js?14a7:268
evaluate @ aurelia-binding.js?1bbb:1517
callSource @ aurelia-binding.js?1bbb:5241
handleEvent @ aurelia-binding.js?1bbb:5250
handleEvent @ aurelia-binding.js?1bbb:3315
message-dialog-view-model.js?ea16:125 message/sequence :  TypeError: Cannot read property 'messages' of undefined
    at eval (webpack-internal:///resources/dialogs/message-dialog/message-dialog-view-model:111:42)
From previous event:
    at MessageDialogViewModel.getSequence (webpack-internal:///resources/dialogs/message-dialog/message-dialog-view-model:102:63)
    at eval (webpack-internal:///resources/dialogs/message-dialog/message-dialog-view-model:50:19)
From previous event:
    at MessageDialogViewModel.activate (webpack-internal:///resources/dialogs/message-dialog/message-dialog-view-model:48:113)
    at tryActivateViewModel (webpack-internal:///13:4848:28)
From previous event:
    at CompositionEngine.createController (webpack-internal:///13:4907:42)
    at CompositionEngine._createControllerAndSwap (webpack-internal:///13:4879:17)
    at CompositionEngine.compose (webpack-internal:///13:4981:19)
    at DialogService.composeAndShowDialog (webpack-internal:///832:87:39)
    at eval (webpack-internal:///832:149:26)
From previous event:
    at DialogService.open (webpack-internal:///832:144:12)
    at eval (webpack-internal:///665:36:33)
From previous event:
    at MessageDialog.open (webpack-internal:///665:35:23)
    at MessagesFailedController.showMessage (webpack-internal:///pages/messages/messages-failed-page:352:28)
    at CallScope.evaluate (webpack-internal:///51:1612:19)
    at Listener.callSource (webpack-internal:///51:5336:40)
    at Listener.handleEvent (webpack-internal:///51:5345:10)
    at DelegateHandlerEntry.handleEvent (webpack-internal:///51:3410:22)

**Comment by mookid8000** [comment]
No longer relevant 🙂
