### ISSUE TITLE
Team filter on overview

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/FleetManager#96]
It would be nice if the Activity Overview had a selector dropdown for teams, if the current user is a member of multiple teams.

![image](https://user-images.githubusercontent.com/32968/105287612-f4d9f680-5bb7-11eb-9a1f-b76e61823c2f.png)

The user's team memberships can be had via `GET /ui/team/membership`.

The list should only be visible if the user is a member of more than 1 team. And in that case, the list should read

* <All Teams>
* My First Team
* My Second Team

defaulting to <All Teams>.

The route to retrieve the overview is `GET /ui/account/overview?stats=today`. I'll extend it to accept a `tid` parameter, which is the team ID. No ID means "all teams".

Regarding the UI, we can use the same mechanism as the one used to change the active queue/machine within the details view

![image](https://user-images.githubusercontent.com/32968/105286953-944ab980-5bb7-11eb-831a-112af3a9abc9.png)

**Comment by anhnicky66** [comment]
@mookid8000 The UI part is done. It will now request `GET /ui/account/overview?stats=today` if "All teams" is selected and `GET /ui/account/overview?stats=today&tid={teamId}` if `Team with {teamId}` is selected.

**Comment by mookid8000** [comment]
Ah cool! I'll see if I can get the server-side stuff done today

**Comment by mookid8000** [comment]
Out in 4.9.3
